# Generated by Django 3.2.7 on 2022-10-20 08:48
#
# Originally used `ckeditor_uploader.fields.RichTextUploadingField` from the
# retired django-ckeditor (CKEditor 4) package. That field is a plain TextField
# at the database level, so `models.TextField` is used here to keep migrations
# runnable without the old package. Migration 0017 switches these fields to
# CKEditor5Field.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default='This is the product', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, default='I am am Amazing Vendor', null=True),
        ),
    ]
